[package]
name = "rust_cryptography_algorithms"
version = "0.1.0"
edition = "2021"

[dependencies]
dusk-poseidon = "0.40.0"
dusk-bls12_381 = "0.13.0"
rand = "0.8.5"
rsa = { version = "0.9.6", features = ["sha2"] }
